name: Itinera
description: "AI tourist platform"
publish_to: 'none' # Private package, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Cupertino icons for iOS
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0   # update to latest null-safe version

flutter_icons:
  android: true
  ios: true
  image_path: "assets/ios-dark.png"

  
flutter:
  uses-material-design: true

  # Add assets here if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Add fonts here if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic